//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalExpense {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalExpense.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All categories.
        /// </summary>
        internal static string AllCategories {
            get {
                return ResourceManager.GetString("AllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an amount greater than zero..
        /// </summary>
        internal static string AmountMustBePositive {
            get {
                return ResourceManager.GetString("AmountMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is required..
        /// </summary>
        internal static string CategoryRequired {
            get {
                return ResourceManager.GetString("CategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV files (*.csv)|*.csv|All files (*.*)|*.*.
        /// </summary>
        internal static string CsvFileFilter {
            get {
                return ResourceManager.GetString("CsvFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the {0} selected transactions?.
        /// </summary>
        internal static string DeleteManyPrompt {
            get {
                return ResourceManager.GetString("DeleteManyPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected transaction?.
        /// </summary>
        internal static string DeleteOnePrompt {
            get {
                return ResourceManager.GetString("DeleteOnePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit transaction.
        /// </summary>
        internal static string EditTransactionTitle {
            get {
                return ResourceManager.GetString("EditTransactionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end date is before the start date..
        /// </summary>
        internal static string EndBeforeStart {
            get {
                return ResourceManager.GetString("EndBeforeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported {0} transactions to {1}..
        /// </summary>
        internal static string ExportDone {
            get {
                return ResourceManager.GetString("ExportDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The export failed and no file was written to {0}: {1}.
        /// </summary>
        internal static string ExportFailed {
            get {
                return ResourceManager.GetString("ExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export transactions.
        /// </summary>
        internal static string ExportTitle {
            get {
                return ResourceManager.GetString("ExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last month.
        /// </summary>
        internal static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last year.
        /// </summary>
        internal static string LastYear {
            get {
                return ResourceManager.GetString("LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        internal static string LegendExpenses {
            get {
                return ResourceManager.GetString("LegendExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        internal static string LegendIncome {
            get {
                return ResourceManager.GetString("LegendIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net.
        /// </summary>
        internal static string LegendNet {
            get {
                return ResourceManager.GetString("LegendNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string PeriodMonth {
            get {
                return ResourceManager.GetString("PeriodMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to {1}.
        /// </summary>
        internal static string PeriodRange {
            get {
                return ResourceManager.GetString("PeriodRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole timeline.
        /// </summary>
        internal static string PeriodTimeline {
            get {
                return ResourceManager.GetString("PeriodTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string PeriodYear {
            get {
                return ResourceManager.GetString("PeriodYear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  (sample data).
        /// </summary>
        internal static string SampleDataTitleSuffix {
            get {
                return ResourceManager.GetString("SampleDataTitleSuffix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string TotalRow {
            get {
                return ResourceManager.GetString("TotalRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That transaction no longer exists..
        /// </summary>
        internal static string TransactionGone {
            get {
                return ResourceManager.GetString("TransactionGone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar chart.
        /// </summary>
        internal static string ViewBarChart {
            get {
                return ResourceManager.GetString("ViewBarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line chart.
        /// </summary>
        internal static string ViewLineChart {
            get {
                return ResourceManager.GetString("ViewLineChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string ViewTable {
            get {
                return ResourceManager.GetString("ViewTable", resourceCulture);
            }
        }
    }
}
